import{useMutation,useQuery,useQueryClient}from'@tanstack/react-query';import{supabase}from'@/lib/supabase';import type{NewsItem,ProcessingJob,Profile,Publication}from'@/lib/database.types';import type{CreateNewsInput,MetricInput,PublicationInput}from'@/lib/schemas';import{toast}from'sonner'
function message(error:unknown){return error instanceof Error?error.message:'Ocorreu um erro inesperado'}
export function useNews(){return useQuery({queryKey:['news'],queryFn:async()=>{const{data,error}=await supabase.from('news_items').select('*,profiles!news_items_assigned_to_fkey(name),categories(name),processing_jobs(*)').is('archived_at',null).order('created_at',{ascending:false});if(error)throw error;return data as unknown as (NewsItem&{profiles:{name:string}|null;categories:{name:string}|null;processing_jobs:ProcessingJob[]})[]}})}
export function useNewsItem(id?:string){return useQuery({queryKey:['news',id],enabled:Boolean(id),queryFn:async()=>{const{data,error}=await supabase.from('news_items').select('*,profiles!news_items_assigned_to_fkey(name),categories(name),processing_jobs(*),news_versions(*),status_history(*),publications(*)').eq('id',id!).single();if(error)throw error;return data}})}
export function useCreateNews(){const qc=useQueryClient();return useMutation({mutationFn:async(input:CreateNewsInput)=>{const{data,error}=await supabase.functions.invoke('process-source-url',{body:input});if(error)throw error;return data as{news_item_id:string;job_id:string}},onSuccess:()=>{qc.invalidateQueries({queryKey:['news']});toast.success('Notícia enviada para processamento')},onError:e=>toast.error(message(e))})}
export function useUpdateNews(){const qc=useQueryClient();return useMutation({mutationFn:async({id,values}:{id:string;values:Record<string,unknown>})=>{const{error}=await supabase.from('news_items').update(values).eq('id',id);if(error)throw error},onSuccess:()=>{qc.invalidateQueries({queryKey:['news']});toast.success('Alterações salvas')},onError:e=>toast.error(message(e))})}
export function usePublications(){return useQuery({queryKey:['publications'],queryFn:async()=>{const{data,error}=await supabase.from('publications').select('*,pages(name),profiles!publications_posted_by_fkey(name),metric_snapshots(*)').is('archived_at',null).order('published_at',{ascending:false});if(error)throw error;return data as unknown as(Publication&{pages:{name:string}|null;profiles:{name:string}|null;metric_snapshots:Record<string,number|string>[]})[]}})}
export function useCreatePublication(){const qc=useQueryClient();return useMutation({mutationFn:async(input:PublicationInput)=>{const{data,error}=await supabase.functions.invoke('create-publication',{body:input});if(error)throw error;return data},onSuccess:()=>{qc.invalidateQueries({queryKey:['publications']});qc.invalidateQueries({queryKey:['dashboard']});toast.success('Publicação registrada')},onError:e=>toast.error(message(e))})}
export function useRecordMetrics(){const qc=useQueryClient();return useMutation({mutationFn:async(input:MetricInput)=>{const{data,error}=await supabase.functions.invoke('record-metrics',{body:input});if(error)throw error;return data},onSuccess:()=>{qc.invalidateQueries({queryKey:['publications']});toast.success('Novo snapshot registrado')},onError:e=>toast.error(message(e))})}
export function useProfiles(){return useQuery({queryKey:['profiles'],queryFn:async()=>{const{data,error}=await supabase.from('profiles').select('*').order('name');if(error)throw error;return data as Profile[]}})}
export function useLookups(){return useQuery({queryKey:['lookups'],queryFn:async()=>{const[c,p,u]=await Promise.all([supabase.from('categories').select('*').eq('is_active',true).order('name'),supabase.from('pages').select('*').eq('is_active',true).order('name'),supabase.from('profiles').select('id,name,role').eq('is_active',true).order('name')]);if(c.error)throw c.error;if(p.error)throw p.error;if(u.error)throw u.error;return{categories:c.data,pages:p.data,profiles:u.data}}})}
export function useDashboard(){return useQuery({queryKey:['dashboard'],queryFn:async()=>{const{data,error}=await supabase.rpc('dashboard_summary',{p_from:null,p_to:null});if(error)throw error;return data as{news_created:number;awaiting_approval:number;approved:number;scheduled:number;publications:number;external_publications:number;daily_goal:number;daily_series:{day:string;total:number}[];top_publications:{title:string;views:number}[]}}})}
