import { useEffect,useState } from "react";
import { CheckCircle2,Clipboard,Download,ExternalLink,LoaderCircle,Newspaper } from "lucide-react";
import { useParams } from "react-router-dom";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Card,CardContent,CardHeader,CardTitle } from "@/components/ui/card";
import { supabase } from "@/lib/supabase";
type Media={url:string;name:string;kind:"video"|"image"};type Item={position:number;title:string;caption:string;source_url:string;media:Media[];media_expired:boolean;media_error:string|null};type Delivery={title:string;sender_name:string;recipient_name:string;recipient_vehicle:string;created_at:string;items:Item[];is_batch:boolean;recipient_confirmed_at:string|null};
export function DistributionDeliveryPage(){const{deliverySlug}=useParams();const[data,setData]=useState<Delivery|null>(null);const[error,setError]=useState("");const[confirming,setConfirming]=useState(false);
useEffect(()=>{supabase.functions.invoke("distribution-delivery",{body:{slug:deliverySlug}}).then(({data:result,error:e})=>{if(e||!result?.items?.length)throw e;setData(result)}).catch(()=>setError("Este link não existe ou não está mais disponível."))},[deliverySlug]);
const copy=async(value:string,label:string)=>{await navigator.clipboard.writeText(value);toast.success(`${label} copiado`)};
const confirmPublished=async()=>{if(!data||data.recipient_confirmed_at||!window.confirm(`Confirmar que ${data.recipient_name} publicou ${data.items.length===1?"este conteúdo":`estas ${data.items.length} notícias`}?`))return;setConfirming(true);const{data:result,error:e}=await supabase.functions.invoke("distribution-delivery",{body:{action:"confirm_published",slug:deliverySlug}});setConfirming(false);if(e||!result?.confirmed)return toast.error("Não foi possível registrar a publicação");setData({...data,recipient_confirmed_at:result.confirmed_at});toast.success(`${result.publication_count||1} publicação(ões) registrada(s) no Copy News`)};
if(error)return <main className="grid min-h-dvh place-items-center p-6 text-center"><div><h1 className="font-display text-2xl font-bold">Link indisponível</h1><p className="mt-2 text-muted-foreground">{error}</p></div></main>;if(!data)return <main className="grid min-h-dvh place-items-center"><LoaderCircle className="animate-spin text-primary"/></main>;
return <main className="min-h-dvh bg-muted/30 p-4 md:p-8"><div className="mx-auto max-w-3xl space-y-5"><header className="flex items-center gap-3"><span className="grid size-11 place-items-center rounded-xl bg-primary text-primary-foreground"><Newspaper/></span><div><p className="font-display text-xl font-bold">Copy News</p><p className="text-sm text-muted-foreground">{data.items.length} {data.items.length===1?"conteúdo enviado":"conteúdos enviados"} por {data.sender_name} para {data.recipient_name}</p></div></header>
{data.items.map((item)=><section key={item.position} className="space-y-3"><div className="flex items-center gap-3"><span className="grid size-8 place-items-center rounded-full bg-primary font-bold text-primary-foreground">{item.position}</span><h2 className="font-display text-xl font-bold">Notícia {item.position}</h2></div><Card><CardHeader><CardTitle className="text-2xl">{item.title}</CardTitle></CardHeader><CardContent className="space-y-5">{item.caption&&<p className="whitespace-pre-wrap leading-7">{item.caption}</p>}<div className="flex flex-wrap gap-2"><Button variant="outline" onClick={()=>copy(item.title,"Título")}><Clipboard/>Copiar título</Button><Button variant="outline" onClick={()=>copy(item.caption,"Legenda")} disabled={!item.caption}><Clipboard/>Copiar legenda</Button><Button variant="outline" onClick={()=>copy(`${item.title}\n\n${item.caption}`.trim(),"Título e legenda")}><Clipboard/>Copiar os dois</Button></div></CardContent></Card><Card><CardHeader><CardTitle>Mídia original</CardTitle></CardHeader><CardContent className="space-y-3">{item.media.map((media,index)=><div key={media.url} className="space-y-2">{media.kind==="video"?<video controls preload="metadata" className="max-h-[560px] w-full rounded-xl bg-black" src={media.url}/>:<img className="max-h-[560px] w-full rounded-xl bg-muted object-contain" src={media.url} alt={`Mídia ${index+1}`}/>}<Button asChild className="w-full"><a href={media.url} download={media.name}><Download/>Baixar {item.media.length>1?`mídia ${index+1}`:"notícia original"}</a></Button></div>)}{!item.media.length&&<p className="text-sm text-muted-foreground">Não foi possível disponibilizar a mídia. O link original continua acessível abaixo.</p>}</CardContent></Card><Button asChild variant="outline" className="w-full"><a href={item.source_url} target="_blank" rel="noreferrer"><ExternalLink/>Abrir publicação original</a></Button></section>)}
<Card><CardContent className="space-y-3 p-5">{data.recipient_confirmed_at?<div className="flex items-center gap-3 text-primary"><CheckCircle2/><div><p className="font-semibold">Publicações confirmadas</p><p className="text-sm text-muted-foreground">Registradas para {data.recipient_name} em {new Date(data.recipient_confirmed_at).toLocaleString("pt-BR")}</p></div></div>:<><p className="font-semibold">Já publicou {data.items.length===1?"este conteúdo":"estas notícias"}?</p><p className="text-sm text-muted-foreground">Ao confirmar, o Copy News registrará {data.items.length} {data.items.length===1?"publicação":"publicações"} para {data.recipient_name}.</p><Button className="w-full" onClick={confirmPublished} disabled={confirming}>{confirming?<LoaderCircle className="animate-spin"/>:<CheckCircle2/>}Marcar como publicado</Button></>}</CardContent></Card></div></main>}
