create extension if not exists pgcrypto;
create schema if not exists private;
revoke all on schema private from public, anon, authenticated;

create type public.user_role as enum ('admin','editor','writer','viewer');
create type public.news_status as enum ('processing','draft','awaiting_approval','changes_requested','approved','scheduled','published','cancelled','archived','failed');
create type public.metric_source as enum ('manual','api');
create type public.publication_source as enum ('copy_news','external');
create type public.job_status as enum ('queued','running','completed','failed','retrying');

create table public.profiles(id uuid primary key references auth.users(id) on delete cascade,name text not null,email text not null unique,role public.user_role not null default 'writer',avatar_url text,is_active boolean not null default true,daily_goal integer check(daily_goal is null or daily_goal>=0),last_seen_at timestamptz,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.pages(id uuid primary key default gen_random_uuid(),name text not null,platform text not null,username text,external_account_id text,is_active boolean not null default true,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.categories(id uuid primary key default gen_random_uuid(),name text not null unique,slug text not null unique,is_active boolean not null default true,created_at timestamptz not null default now());
create table public.news_items(id uuid primary key default gen_random_uuid(),source_url text not null,source_platform text,source_author text,source_caption text,source_credit text,temporary_media_path text,temporary_media_expires_at timestamptz,transcript text,transcript_language text,ocr_text text,ocr_confidence numeric(5,4),generated_title text,generated_caption text,summary text,ai_confidence text check(ai_confidence in('low','medium','high')),ai_warnings jsonb not null default '[]',detected_facts jsonb not null default '[]',status public.news_status not null default 'processing',category_id uuid references public.categories(id) on delete set null,destination_page_id uuid references public.pages(id) on delete set null,assigned_to uuid references public.profiles(id) on delete set null,created_by uuid not null references public.profiles(id),scheduled_at timestamptz,approved_by uuid references public.profiles(id) on delete set null,approved_at timestamptz,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),archived_at timestamptz,constraint scheduled_requires_date check(status<>'scheduled' or scheduled_at is not null));
create table public.news_versions(id uuid primary key default gen_random_uuid(),news_item_id uuid not null references public.news_items(id) on delete cascade,field text not null check(field in('title','caption')),previous_value text,new_value text not null,change_type text not null check(change_type in('manual','ai','regenerate')),instruction text,created_by uuid not null references public.profiles(id),created_at timestamptz not null default now());
create table public.status_history(id uuid primary key default gen_random_uuid(),news_item_id uuid not null references public.news_items(id) on delete cascade,from_status public.news_status,to_status public.news_status not null,note text,changed_by uuid not null references public.profiles(id),created_at timestamptz not null default now());
create table public.publications(id uuid primary key default gen_random_uuid(),news_item_id uuid references public.news_items(id) on delete set null,title text not null,caption text,platform text not null,page_id uuid references public.pages(id) on delete set null,published_url text not null,external_media_id text,published_at timestamptz not null,posted_by uuid references public.profiles(id) on delete set null,credit_text text,source_type public.publication_source not null default 'external',notes text,created_by uuid not null references public.profiles(id),created_at timestamptz not null default now(),updated_at timestamptz not null default now(),archived_at timestamptz);
create unique index publications_url_unique on public.publications(lower(published_url)) where published_url<>'' and archived_at is null;
create table public.metric_snapshots(id uuid primary key default gen_random_uuid(),publication_id uuid not null references public.publications(id) on delete cascade,captured_at timestamptz not null default now(),source public.metric_source not null default 'manual',views bigint not null default 0 check(views>=0),reach bigint not null default 0 check(reach>=0),impressions bigint not null default 0 check(impressions>=0),likes bigint not null default 0 check(likes>=0),comments bigint not null default 0 check(comments>=0),shares bigint not null default 0 check(shares>=0),saves bigint not null default 0 check(saves>=0),clicks bigint not null default 0 check(clicks>=0),followers_gained bigint not null default 0 check(followers_gained>=0),raw_payload jsonb not null default '{}',created_by uuid not null references public.profiles(id),created_at timestamptz not null default now());
create table public.processing_jobs(id uuid primary key default gen_random_uuid(),news_item_id uuid not null references public.news_items(id) on delete cascade,current_step text not null default 'validate_url',status public.job_status not null default 'queued',progress integer not null default 0 check(progress between 0 and 100),attempts integer not null default 0,error_code text,error_message text,step_results jsonb not null default '{}',lease_owner text,lease_expires_at timestamptz,started_at timestamptz,finished_at timestamptz,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.connected_accounts(id uuid primary key default gen_random_uuid(),page_id uuid not null references public.pages(id) on delete cascade,provider text not null,provider_account_id text not null,encrypted_access_token text not null,token_expires_at timestamptz,scopes text[] not null default '{}',status text not null default 'disconnected',last_sync_at timestamptz,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(provider,provider_account_id));
create table public.audit_logs(id uuid primary key default gen_random_uuid(),user_id uuid references public.profiles(id) on delete set null,action text not null,entity_type text not null,entity_id uuid,before_data jsonb,after_data jsonb,created_at timestamptz not null default now());

create index news_items_created_by_idx on public.news_items(created_by);create index news_items_assigned_to_idx on public.news_items(assigned_to);create index news_items_status_idx on public.news_items(status);create index news_items_created_at_idx on public.news_items(created_at desc);create index publications_published_at_idx on public.publications(published_at desc);create index metric_snapshots_publication_idx on public.metric_snapshots(publication_id,captured_at desc);create index processing_jobs_queue_idx on public.processing_jobs(status,created_at) where status in('queued','retrying');

create function private.current_profile() returns public.profiles language sql stable security definer set search_path='' as $$select p from public.profiles p where p.id=(select auth.uid()) and p.is_active$$;
create function private.current_role() returns public.user_role language sql stable security definer set search_path='' as $$select role from public.profiles where id=(select auth.uid()) and is_active$$;
create function private.is_active() returns boolean language sql stable security definer set search_path='' as $$select exists(select 1 from public.profiles where id=(select auth.uid()) and is_active)$$;
grant execute on function private.current_role() to authenticated;grant execute on function private.is_active() to authenticated;

create function private.handle_new_user() returns trigger language plpgsql security definer set search_path='' as $$begin insert into public.profiles(id,name,email,role) values(new.id,coalesce(new.raw_user_meta_data->>'name',split_part(new.email,'@',1)),new.email,coalesce((new.raw_app_meta_data->>'role')::public.user_role,'writer'));return new;end$$;
create trigger on_auth_user_created after insert on auth.users for each row execute function private.handle_new_user();
create function private.touch_updated_at() returns trigger language plpgsql set search_path='' as $$begin new.updated_at=now();return new;end$$;
create trigger profiles_touch before update on public.profiles for each row execute function private.touch_updated_at();create trigger pages_touch before update on public.pages for each row execute function private.touch_updated_at();create trigger news_touch before update on public.news_items for each row execute function private.touch_updated_at();create trigger pubs_touch before update on public.publications for each row execute function private.touch_updated_at();create trigger jobs_touch before update on public.processing_jobs for each row execute function private.touch_updated_at();
create function private.audit_news_change() returns trigger language plpgsql security definer set search_path='' as $$begin if old.status is distinct from new.status then insert into public.status_history(news_item_id,from_status,to_status,changed_by) values(new.id,old.status,new.status,(select auth.uid()));end if;if old.generated_title is distinct from new.generated_title and new.generated_title is not null then insert into public.news_versions(news_item_id,field,previous_value,new_value,change_type,created_by) values(new.id,'title',old.generated_title,new.generated_title,'manual',coalesce((select auth.uid()),new.created_by));end if;if old.generated_caption is distinct from new.generated_caption and new.generated_caption is not null then insert into public.news_versions(news_item_id,field,previous_value,new_value,change_type,created_by) values(new.id,'caption',old.generated_caption,new.generated_caption,'manual',coalesce((select auth.uid()),new.created_by));end if;return new;end$$;
create trigger audit_news_update after update on public.news_items for each row execute function private.audit_news_change();

alter table public.profiles enable row level security;alter table public.pages enable row level security;alter table public.categories enable row level security;alter table public.news_items enable row level security;alter table public.news_versions enable row level security;alter table public.status_history enable row level security;alter table public.publications enable row level security;alter table public.metric_snapshots enable row level security;alter table public.processing_jobs enable row level security;alter table public.connected_accounts enable row level security;alter table public.audit_logs enable row level security;
create policy profiles_read on public.profiles for select to authenticated using(private.is_active());create policy profiles_admin_update on public.profiles for update to authenticated using(private.current_role()='admin') with check(private.current_role()='admin');
create policy lookups_read_pages on public.pages for select to authenticated using(private.is_active());create policy lookups_write_pages on public.pages for all to authenticated using(private.current_role() in('admin','editor')) with check(private.current_role() in('admin','editor'));create policy lookups_read_categories on public.categories for select to authenticated using(private.is_active());create policy lookups_write_categories on public.categories for all to authenticated using(private.current_role() in('admin','editor')) with check(private.current_role() in('admin','editor'));
create policy news_read on public.news_items for select to authenticated using(private.is_active() and (private.current_role() in('admin','editor','viewer') or created_by=(select auth.uid()) or assigned_to=(select auth.uid())));create policy news_insert on public.news_items for insert to authenticated with check(private.current_role() in('admin','editor','writer') and created_by=(select auth.uid()));create policy news_update on public.news_items for update to authenticated using(private.current_role() in('admin','editor') or (private.current_role()='writer' and (created_by=(select auth.uid()) or assigned_to=(select auth.uid())))) with check(private.current_role() in('admin','editor') or (private.current_role()='writer' and (created_by=(select auth.uid()) or assigned_to=(select auth.uid()))));create policy news_delete on public.news_items for delete to authenticated using(private.current_role()='admin');
create policy versions_read on public.news_versions for select to authenticated using(exists(select 1 from public.news_items n where n.id=news_item_id));create policy versions_write on public.news_versions for insert to authenticated with check(private.current_role() in('admin','editor','writer') and created_by=(select auth.uid()));create policy history_read on public.status_history for select to authenticated using(exists(select 1 from public.news_items n where n.id=news_item_id));
create policy publications_read on public.publications for select to authenticated using(private.is_active());create policy publications_write on public.publications for insert to authenticated with check(private.current_role() in('admin','editor','writer') and created_by=(select auth.uid()));create policy publications_update on public.publications for update to authenticated using(private.current_role() in('admin','editor') or created_by=(select auth.uid())) with check(private.current_role() in('admin','editor') or created_by=(select auth.uid()));create policy publications_delete on public.publications for delete to authenticated using(private.current_role()='admin');
create policy metrics_read on public.metric_snapshots for select to authenticated using(private.is_active());create policy metrics_write on public.metric_snapshots for insert to authenticated with check(private.current_role() in('admin','editor','writer') and created_by=(select auth.uid()));
create policy jobs_read on public.processing_jobs for select to authenticated using(exists(select 1 from public.news_items n where n.id=news_item_id));create policy jobs_insert on public.processing_jobs for insert to authenticated with check(exists(select 1 from public.news_items n where n.id=news_item_id and n.created_by=(select auth.uid())));
create policy accounts_admin on public.connected_accounts for all to authenticated using(private.current_role()='admin') with check(private.current_role()='admin');create policy audit_admin_read on public.audit_logs for select to authenticated using(private.current_role()='admin');

insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types) values('temporary-media','temporary-media',false,104857600,array['video/mp4','video/webm','video/quicktime','audio/mpeg','audio/mp4','audio/wav','image/jpeg','image/png']) on conflict(id) do update set public=false,file_size_limit=excluded.file_size_limit,allowed_mime_types=excluded.allowed_mime_types;
create policy temp_media_read on storage.objects for select to authenticated using(bucket_id='temporary-media' and private.is_active());

create or replace function public.dashboard_summary(p_from timestamptz default null,p_to timestamptz default null)
returns jsonb language sql stable security invoker set search_path='' as $$
with bounds as (
  select
    coalesce(p_from, date_trunc('day', now() at time zone 'America/Maceio') at time zone 'America/Maceio') as dfrom,
    coalesce(p_to, (date_trunc('day', now() at time zone 'America/Maceio') + interval '1 day') at time zone 'America/Maceio') as dto
), days as (
  select generate_series((select dfrom from bounds) - interval '6 days', (select dfrom from bounds), interval '1 day') as day_start
), series as (
  select to_char(d.day_start at time zone 'America/Maceio','DD/MM') as label, count(p.id)::int as total
  from days d
  left join public.publications p on p.published_at >= d.day_start and p.published_at < d.day_start + interval '1 day' and p.archived_at is null
  group by d.day_start order by d.day_start
), latest as (
  select distinct on(ms.publication_id) ms.publication_id, ms.views
  from public.metric_snapshots ms order by ms.publication_id, ms.captured_at desc
)
select jsonb_build_object(
  'news_created',(select count(*) from public.news_items,bounds where created_at>=dfrom and created_at<dto),
  'awaiting_approval',(select count(*) from public.news_items where status='awaiting_approval'),
  'approved',(select count(*) from public.news_items,bounds where status='approved' and updated_at>=dfrom and updated_at<dto),
  'scheduled',(select count(*) from public.news_items where status='scheduled'),
  'publications',(select count(*) from public.publications,bounds where published_at>=dfrom and published_at<dto and archived_at is null),
  'external_publications',(select count(*) from public.publications,bounds where source_type='external' and published_at>=dfrom and published_at<dto and archived_at is null),
  'daily_goal',coalesce((select sum(daily_goal) from public.profiles where is_active),0),
  'daily_series',(select coalesce(jsonb_agg(jsonb_build_object('day',label,'total',total)),'[]'::jsonb) from series),
  'top_publications',(select coalesce(jsonb_agg(x),'[]'::jsonb) from(select p.title,l.views from latest l join public.publications p on p.id=l.publication_id order by l.views desc limit 5)x)
)$$;
grant execute on function public.dashboard_summary(timestamptz,timestamptz) to authenticated;

insert into public.categories(name,slug) values('Política','politica'),('Cidades','cidades'),('Economia','economia'),('Polícia','policia'),('Esportes','esportes'),('Entretenimento','entretenimento'),('Geral','geral') on conflict do nothing;
